"""Create courses table

Revision ID: 16fb51a65be1
Revises: 9b29f4a8f119
Create Date: 2025-01-27 18:02:34.433097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fb51a65be1'
down_revision: Union[str, None] = '9b29f4a8f119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_id', table_name='videos')
    op.drop_index('ix_videos_title', table_name='videos')
    op.drop_table('videos')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('s3_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_title', 'videos', ['title'], unique=False)
    op.create_index('ix_videos_id', 'videos', ['id'], unique=False)
    # ### end Alembic commands ###
