"""Initial migration

Revision ID: fee2ce3afe8d
Revises: 
Create Date: 2025-01-09 18:32:57.790931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee2ce3afe8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_videos_id', table_name='videos')
    op.drop_index('ix_videos_title', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('s3_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_title', 'videos', ['title'], unique=False)
    op.create_index('ix_videos_id', 'videos', ['id'], unique=False)
    # ### end Alembic commands ###
