name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tutorials-app:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tutorials-app:latest

      - name: Decode EC2_PRIVATE_KEY
        run: echo "${{ secrets.EC2_PRIVATE_KEY }}" | base64 --decode > private_key.pem
        
      - name: Set Permissions on the Key
        run: chmod 400 private_key.pem
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          key_path: private_key.pem  # Use the decoded private key file
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/tutorials-app:latest
            docker stop tutorials-app || true
            docker rm tutorials-app || true
            docker run -d --env-file /home/ubuntu/myapp/.env -p 8000:8000 --name tutorials-app ${{ secrets.DOCKER_USERNAME }}/tutorials-app:latest
      
